// Fixture completo del Mundial 2026 (En horas de Colombia - America/Bogota UTC-5)
// dateUtc es en UTC real, el JS lo convierte a Colombia en pantalla.
// Grupos basados en el fixture oficial confirmado por la imagen.

const matches = [
    // ===== FASE DE GRUPOS =====
    // GRUPO A: México, Sudáfrica, Corea del Sur, Ganador UEFA D
    { id: 1, phase: "Fase de Grupos", group: "Grupo A", dateUtc: "2026-06-11T19:00:00Z", team1: { name: "México", flag: "🇲🇽" }, team2: { name: "Sudáfrica", flag: "🇿🇦" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 2, phase: "Fase de Grupos", group: "Grupo A", dateUtc: "2026-06-12T02:00:00Z", team1: { name: "Corea del Sur", flag: "🇰🇷" }, team2: { name: "Gan. UEFA D", flag: "🏳️" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 3, phase: "Fase de Grupos", group: "Grupo A", dateUtc: "2026-06-18T16:00:00Z", team1: { name: "Sudáfrica", flag: "🇿🇦" }, team2: { name: "Gan. UEFA D", flag: "🏳️" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 4, phase: "Fase de Grupos", group: "Grupo A", dateUtc: "2026-06-18T21:00:00Z", team1: { name: "México", flag: "🇲🇽" }, team2: { name: "Corea del Sur", flag: "🇰🇷" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 5, phase: "Fase de Grupos", group: "Grupo A", dateUtc: "2026-06-24T17:00:00Z", team1: { name: "Gan. UEFA D", flag: "🏳️" }, team2: { name: "México", flag: "🇲🇽" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 6, phase: "Fase de Grupos", group: "Grupo A", dateUtc: "2026-06-24T21:00:00Z", team1: { name: "Sudáfrica", flag: "🇿🇦" }, team2: { name: "República de Corea", flag: "🇰🇷" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },

    // GRUPO B: Canadá, Gan. UEFA B, Suiza, Catar
    { id: 7, phase: "Fase de Grupos", group: "Grupo B", dateUtc: "2026-06-12T19:00:00Z", team1: { name: "Canadá", flag: "🇨🇦" }, team2: { name: "Gan. UEFA B", flag: "🏳️" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 8, phase: "Fase de Grupos", group: "Grupo B", dateUtc: "2026-06-13T02:00:00Z", team1: { name: "Catar", flag: "🇶🇦" }, team2: { name: "Suiza", flag: "🇨🇭" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 9, phase: "Fase de Grupos", group: "Grupo B", dateUtc: "2026-06-18T07:00:00Z", team1: { name: "Gan. UEFA B", flag: "🏳️" }, team2: { name: "Suiza", flag: "🇨🇭" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 10, phase: "Fase de Grupos", group: "Grupo B", dateUtc: "2026-06-18T10:00:00Z", team1: { name: "Canadá", flag: "🇨🇦" }, team2: { name: "Catar", flag: "🇶🇦" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 11, phase: "Fase de Grupos", group: "Grupo B", dateUtc: "2026-06-24T16:00:00Z", team1: { name: "Suiza", flag: "🇨🇭" }, team2: { name: "Canadá", flag: "🇨🇦" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 12, phase: "Fase de Grupos", group: "Grupo B", dateUtc: "2026-06-24T19:00:00Z", team1: { name: "Gan. UEFA B", flag: "🏳️" }, team2: { name: "Catar", flag: "🇶🇦" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },

    // GRUPO C: Brasil, Marruecos, Escocia, Haití
    { id: 13, phase: "Fase de Grupos", group: "Grupo C", dateUtc: "2026-06-13T22:00:00Z", team1: { name: "Brasil", flag: "🇧🇷" }, team2: { name: "Marruecos", flag: "🇲🇦" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 14, phase: "Fase de Grupos", group: "Grupo C", dateUtc: "2026-06-14T01:00:00Z", team1: { name: "Haití", flag: "🇭🇹" }, team2: { name: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 15, phase: "Fase de Grupos", group: "Grupo C", dateUtc: "2026-06-19T12:00:00Z", team1: { name: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" }, team2: { name: "Marruecos", flag: "🇲🇦" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 16, phase: "Fase de Grupos", group: "Grupo C", dateUtc: "2026-06-20T01:00:00Z", team1: { name: "Brasil", flag: "🇧🇷" }, team2: { name: "Haití", flag: "🇭🇹" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 17, phase: "Fase de Grupos", group: "Grupo C", dateUtc: "2026-06-24T22:00:00Z", team1: { name: "Marruecos", flag: "🇲🇦" }, team2: { name: "Haití", flag: "🇭🇹" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 18, phase: "Fase de Grupos", group: "Grupo C", dateUtc: "2026-06-24T22:00:00Z", team1: { name: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" }, team2: { name: "Brasil", flag: "🇧🇷" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },

    // GRUPO D: Alemania, Curazao, Países Bajos, Japón
    { id: 19, phase: "Fase de Grupos", group: "Grupo D", dateUtc: "2026-06-14T17:00:00Z", team1: { name: "Alemania", flag: "🇩🇪" }, team2: { name: "Curazao", flag: "🇨🇼" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 20, phase: "Fase de Grupos", group: "Grupo D", dateUtc: "2026-06-14T20:00:00Z", team1: { name: "Países Bajos", flag: "🇳🇱" }, team2: { name: "Japón", flag: "🇯🇵" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 21, phase: "Fase de Grupos", group: "Grupo D", dateUtc: "2026-06-20T17:00:00Z", team1: { name: "Alemania", flag: "🇩🇪" }, team2: { name: "Costa de Marfil", flag: "🇨🇮" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 22, phase: "Fase de Grupos", group: "Grupo D", dateUtc: "2026-06-21T04:00:00Z", team1: { name: "Túnez", flag: "🇹🇳" }, team2: { name: "Japón", flag: "🇯🇵" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 23, phase: "Fase de Grupos", group: "Grupo D", dateUtc: "2026-06-25T20:00:00Z", team1: { name: "Ecuador", flag: "🇪🇨" }, team2: { name: "Alemania", flag: "🇩🇪" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 24, phase: "Fase de Grupos", group: "Grupo D", dateUtc: "2026-06-25T23:00:00Z", team1: { name: "Túnez", flag: "🇹🇳" }, team2: { name: "Países Bajos", flag: "🇳🇱" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },

    // GRUPO E: Costa de Marfil, Ecuador, Túnez, Gan. UEFA B
    { id: 25, phase: "Fase de Grupos", group: "Grupo E", dateUtc: "2026-06-14T23:00:00Z", team1: { name: "Costa de Marfil", flag: "🇨🇮" }, team2: { name: "Ecuador", flag: "🇪🇨" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 26, phase: "Fase de Grupos", group: "Grupo E", dateUtc: "2026-06-15T02:00:00Z", team1: { name: "Gan. UEFA B", flag: "🏳️" }, team2: { name: "Túnez", flag: "🇹🇳" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 27, phase: "Fase de Grupos", group: "Grupo E", dateUtc: "2026-06-25T08:00:00Z", team1: { name: "Curazao", flag: "🇨🇼" }, team2: { name: "Costa de Marfil", flag: "🇨🇮" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 28, phase: "Fase de Grupos", group: "Grupo E", dateUtc: "2026-06-25T11:00:00Z", team1: { name: "Japón", flag: "🇯🇵" }, team2: { name: "Gan. UEFA B", flag: "🏳️" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 29, phase: "Fase de Grupos", group: "Grupo E", dateUtc: "2026-06-26T27:00:00Z", team1: { name: "Ecuador", flag: "🇪🇨" }, team2: { name: "Curazao", flag: "🇨🇼" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },

    // GRUPO F: España, Cabo Verde, Arabia Saudí, Uruguay
    { id: 30, phase: "Fase de Grupos", group: "Grupo F", dateUtc: "2026-06-15T16:00:00Z", team1: { name: "España", flag: "🇪🇸" }, team2: { name: "Cabo Verde", flag: "🇨🇻" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 31, phase: "Fase de Grupos", group: "Grupo F", dateUtc: "2026-06-15T10:00:00Z", team1: { name: "Arabia Saudí", flag: "🇸🇦" }, team2: { name: "Uruguay", flag: "🇺🇾" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 32, phase: "Fase de Grupos", group: "Grupo F", dateUtc: "2026-06-21T16:00:00Z", team1: { name: "España", flag: "🇪🇸" }, team2: { name: "Arabia Saudí", flag: "🇸🇦" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 33, phase: "Fase de Grupos", group: "Grupo F", dateUtc: "2026-06-21T10:00:00Z", team1: { name: "Uruguay", flag: "🇺🇾" }, team2: { name: "Cabo Verde", flag: "🇨🇻" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 34, phase: "Fase de Grupos", group: "Grupo F", dateUtc: "2026-06-26T24:00:00Z", team1: { name: "Uruguay", flag: "🇺🇾" }, team2: { name: "España", flag: "🇪🇸" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 35, phase: "Fase de Grupos", group: "Grupo F", dateUtc: "2026-06-26T24:00:00Z", team1: { name: "Cabo Verde", flag: "🇨🇻" }, team2: { name: "Arabia Saudí", flag: "🇸🇦" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },

    // GRUPO G: Francia, Senegal, Gan. FIFA II, Noruega
    { id: 36, phase: "Fase de Grupos", group: "Grupo G", dateUtc: "2026-06-16T19:00:00Z", team1: { name: "Francia", flag: "🇫🇷" }, team2: { name: "Senegal", flag: "🇸🇳" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 37, phase: "Fase de Grupos", group: "Grupo G", dateUtc: "2026-06-16T22:00:00Z", team1: { name: "Gan. FIFA II", flag: "🏳️" }, team2: { name: "Noruega", flag: "🇳🇴" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 38, phase: "Fase de Grupos", group: "Grupo G", dateUtc: "2026-06-22T09:00:00Z", team1: { name: "Francia", flag: "🇫🇷" }, team2: { name: "Gan. FIFA II", flag: "🏳️" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 39, phase: "Fase de Grupos", group: "Grupo G", dateUtc: "2026-06-22T12:00:00Z", team1: { name: "Noruega", flag: "🇳🇴" }, team2: { name: "Senegal", flag: "🇸🇳" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 40, phase: "Fase de Grupos", group: "Grupo G", dateUtc: "2026-06-26T07:00:00Z", team1: { name: "Noruega", flag: "🇳🇴" }, team2: { name: "Francia", flag: "🇫🇷" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 41, phase: "Fase de Grupos", group: "Grupo G", dateUtc: "2026-06-26T07:00:00Z", team1: { name: "Senegal", flag: "🇸🇳" }, team2: { name: "Gan. FIFA II", flag: "🏳️" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },

    // GRUPO H: Argentina, Argelia, Austria, Jordania
    { id: 42, phase: "Fase de Grupos", group: "Grupo H", dateUtc: "2026-06-16T13:00:00Z", team1: { name: "Argentina", flag: "🇦🇷" }, team2: { name: "Argelia", flag: "🇩🇿" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 43, phase: "Fase de Grupos", group: "Grupo H", dateUtc: "2026-06-17T04:00:00Z", team1: { name: "Austria", flag: "🇦🇹" }, team2: { name: "Jordania", flag: "🇯🇴" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 44, phase: "Fase de Grupos", group: "Grupo H", dateUtc: "2026-06-22T17:00:00Z", team1: { name: "Argentina", flag: "🇦🇷" }, team2: { name: "Austria", flag: "🇦🇹" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 45, phase: "Fase de Grupos", group: "Grupo H", dateUtc: "2026-06-22T15:00:00Z", team1: { name: "Jordania", flag: "🇯🇴" }, team2: { name: "Argelia", flag: "🇩🇿" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 46, phase: "Fase de Grupos", group: "Grupo H", dateUtc: "2026-06-27T04:00:00Z", team1: { name: "Jordania", flag: "🇯🇴" }, team2: { name: "Argentina", flag: "🇦🇷" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 47, phase: "Fase de Grupos", group: "Grupo H", dateUtc: "2026-06-27T04:00:00Z", team1: { name: "Argelia", flag: "🇩🇿" }, team2: { name: "Austria", flag: "🇦🇹" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },

    // GRUPO I: Portugal, Uzbekistán, Gan. FIFA I, Colombia
    { id: 48, phase: "Fase de Grupos", group: "Grupo I", dateUtc: "2026-06-17T17:00:00Z", team1: { name: "Portugal", flag: "🇵🇹" }, team2: { name: "Gan. FIFA I", flag: "🏳️" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 49, phase: "Fase de Grupos", group: "Grupo I", dateUtc: "2026-06-18T02:00:00Z", team1: { name: "Uzbekistán", flag: "🇺🇿" }, team2: { name: "Colombia", flag: "🇨🇴" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 50, phase: "Fase de Grupos", group: "Grupo I", dateUtc: "2026-06-23T17:00:00Z", team1: { name: "Portugal", flag: "🇵🇹" }, team2: { name: "Uzbekistán", flag: "🇺🇿" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 51, phase: "Fase de Grupos", group: "Grupo I", dateUtc: "2026-06-24T02:00:00Z", team1: { name: "Colombia", flag: "🇨🇴" }, team2: { name: "Gan. FIFA I", flag: "🏳️" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 52, phase: "Fase de Grupos", group: "Grupo I", dateUtc: "2026-06-27T23:30:00Z", team1: { name: "Colombia", flag: "🇨🇴" }, team2: { name: "Portugal", flag: "🇵🇹" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 53, phase: "Fase de Grupos", group: "Grupo I", dateUtc: "2026-06-27T23:30:00Z", team1: { name: "Gan. Torneo I", flag: "🏳️" }, team2: { name: "Uzbekistán", flag: "🇺🇿" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },

    // GRUPO J: Inglaterra, Croacia, Ghana, Panamá
    { id: 54, phase: "Fase de Grupos", group: "Grupo J", dateUtc: "2026-06-17T20:00:00Z", team1: { name: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" }, team2: { name: "Croacia", flag: "🇭🇷" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 55, phase: "Fase de Grupos", group: "Grupo J", dateUtc: "2026-06-17T23:00:00Z", team1: { name: "Ghana", flag: "🇬🇭" }, team2: { name: "Panamá", flag: "🇵🇦" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 56, phase: "Fase de Grupos", group: "Grupo J", dateUtc: "2026-06-23T20:00:00Z", team1: { name: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" }, team2: { name: "Ghana", flag: "🇬🇭" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 57, phase: "Fase de Grupos", group: "Grupo J", dateUtc: "2026-06-23T23:00:00Z", team1: { name: "Panamá", flag: "🇵🇦" }, team2: { name: "Croacia", flag: "🇭🇷" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 58, phase: "Fase de Grupos", group: "Grupo J", dateUtc: "2026-06-27T21:00:00Z", team1: { name: "Panamá", flag: "🇵🇦" }, team2: { name: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 59, phase: "Fase de Grupos", group: "Grupo J", dateUtc: "2026-06-27T21:00:00Z", team1: { name: "Croacia", flag: "🇭🇷" }, team2: { name: "Ghana", flag: "🇬🇭" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },

    // GRUPO K: Estados Unidos, Paraguay, Australia, Gan. UEFA C
    { id: 60, phase: "Fase de Grupos", group: "Grupo K", dateUtc: "2026-06-12T13:00:00Z", team1: { name: "Estados Unidos", flag: "🇺🇸" }, team2: { name: "Paraguay", flag: "🇵🇾" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 61, phase: "Fase de Grupos", group: "Grupo K", dateUtc: "2026-06-14T04:00:00Z", team1: { name: "Australia", flag: "🇦🇺" }, team2: { name: "Gan. UEFA C", flag: "🏳️" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 62, phase: "Fase de Grupos", group: "Grupo K", dateUtc: "2026-06-19T19:00:00Z", team1: { name: "Estados Unidos", flag: "🇺🇸" }, team2: { name: "Australia", flag: "🇦🇺" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 63, phase: "Fase de Grupos", group: "Grupo K", dateUtc: "2026-06-20T04:00:00Z", team1: { name: "Gan. UEFA C", flag: "🏳️" }, team2: { name: "Paraguay", flag: "🇵🇾" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 64, phase: "Fase de Grupos", group: "Grupo K", dateUtc: "2026-06-25T04:00:00Z", team1: { name: "Paraguay", flag: "🇵🇾" }, team2: { name: "Australia", flag: "🇦🇺" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 65, phase: "Fase de Grupos", group: "Grupo K", dateUtc: "2026-06-25T04:00:00Z", team1: { name: "Gan. UEFA C", flag: "🏳️" }, team2: { name: "Estados Unidos", flag: "🇺🇸" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },

    // GRUPO L: Bélgica, Egipto, RI de Irán, Nueva Zelanda
    { id: 66, phase: "Fase de Grupos", group: "Grupo L", dateUtc: "2026-06-15T19:00:00Z", team1: { name: "Bélgica", flag: "🇧🇪" }, team2: { name: "Egipto", flag: "🇪🇬" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 67, phase: "Fase de Grupos", group: "Grupo L", dateUtc: "2026-06-16T01:00:00Z", team1: { name: "RI de Irán", flag: "🇮🇷" }, team2: { name: "Nueva Zelanda", flag: "🇳🇿" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 68, phase: "Fase de Grupos", group: "Grupo L", dateUtc: "2026-06-21T19:00:00Z", team1: { name: "Bélgica", flag: "🇧🇪" }, team2: { name: "RI de Irán", flag: "🇮🇷" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 69, phase: "Fase de Grupos", group: "Grupo L", dateUtc: "2026-06-21T13:00:00Z", team1: { name: "Nueva Zelanda", flag: "🇳🇿" }, team2: { name: "Egipto", flag: "🇪🇬" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 70, phase: "Fase de Grupos", group: "Grupo L", dateUtc: "2026-06-26T03:00:00Z", team1: { name: "Nueva Zelanda", flag: "🇳🇿" }, team2: { name: "Bélgica", flag: "🇧🇪" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 71, phase: "Fase de Grupos", group: "Grupo L", dateUtc: "2026-06-26T03:00:00Z", team1: { name: "Egipto", flag: "🇪🇬" }, team2: { name: "RI de Irán", flag: "🇮🇷" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },

    // ===== DIECISEISAVOS DE FINAL (16 partidos) =====
    { id: 72, phase: "Dieciseisavos de Final", group: "Eliminatorias", dateUtc: "2026-06-28T19:00:00Z", team1: { name: "1ro Grupo A", flag: "❓" }, team2: { name: "Mejor 3ro", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 73, phase: "Dieciseisavos de Final", group: "Eliminatorias", dateUtc: "2026-06-28T23:00:00Z", team1: { name: "1ro Grupo B", flag: "❓" }, team2: { name: "2do Grupo F", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 74, phase: "Dieciseisavos de Final", group: "Eliminatorias", dateUtc: "2026-06-29T19:00:00Z", team1: { name: "1ro Grupo C", flag: "❓" }, team2: { name: "2do Grupo G", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 75, phase: "Dieciseisavos de Final", group: "Eliminatorias", dateUtc: "2026-06-29T23:00:00Z", team1: { name: "1ro Grupo D", flag: "❓" }, team2: { name: "Mejor 3ro", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 76, phase: "Dieciseisavos de Final", group: "Eliminatorias", dateUtc: "2026-06-30T19:00:00Z", team1: { name: "1ro Grupo E", flag: "❓" }, team2: { name: "Mejor 3ro", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 77, phase: "Dieciseisavos de Final", group: "Eliminatorias", dateUtc: "2026-06-30T23:00:00Z", team1: { name: "1ro Grupo F", flag: "❓" }, team2: { name: "2do Grupo A", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 78, phase: "Dieciseisavos de Final", group: "Eliminatorias", dateUtc: "2026-07-01T19:00:00Z", team1: { name: "1ro Grupo G", flag: "❓" }, team2: { name: "2do Grupo B", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 79, phase: "Dieciseisavos de Final", group: "Eliminatorias", dateUtc: "2026-07-01T23:00:00Z", team1: { name: "1ro Grupo H", flag: "❓" }, team2: { name: "Mejor 3ro", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 80, phase: "Dieciseisavos de Final", group: "Eliminatorias", dateUtc: "2026-07-02T19:00:00Z", team1: { name: "1ro Grupo I", flag: "❓" }, team2: { name: "Mejor 3ro", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 81, phase: "Dieciseisavos de Final", group: "Eliminatorias", dateUtc: "2026-07-02T23:00:00Z", team1: { name: "1ro Grupo J", flag: "❓" }, team2: { name: "2do Grupo C", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 82, phase: "Dieciseisavos de Final", group: "Eliminatorias", dateUtc: "2026-07-03T19:00:00Z", team1: { name: "1ro Grupo K", flag: "❓" }, team2: { name: "2do Grupo D", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 83, phase: "Dieciseisavos de Final", group: "Eliminatorias", dateUtc: "2026-07-03T23:00:00Z", team1: { name: "1ro Grupo L", flag: "❓" }, team2: { name: "Mejor 3ro", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 84, phase: "Dieciseisavos de Final", group: "Eliminatorias", dateUtc: "2026-07-04T19:00:00Z", team1: { name: "2do Grupo E", flag: "❓" }, team2: { name: "2do Grupo H", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 85, phase: "Dieciseisavos de Final", group: "Eliminatorias", dateUtc: "2026-07-04T23:00:00Z", team1: { name: "2do Grupo I", flag: "❓" }, team2: { name: "2do Grupo J", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 86, phase: "Dieciseisavos de Final", group: "Eliminatorias", dateUtc: "2026-07-05T19:00:00Z", team1: { name: "2do Grupo K", flag: "❓" }, team2: { name: "Mejor 3ro", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 87, phase: "Dieciseisavos de Final", group: "Eliminatorias", dateUtc: "2026-07-05T23:00:00Z", team1: { name: "2do Grupo L", flag: "❓" }, team2: { name: "Mejor 3ro", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },

    // ===== OCTAVOS DE FINAL (8 partidos) =====
    { id: 88, phase: "Octavos de Final", group: "Eliminatorias", dateUtc: "2026-07-04T19:00:00Z", team1: { name: "Gan. R32-A", flag: "❓" }, team2: { name: "Gan. R32-B", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 89, phase: "Octavos de Final", group: "Eliminatorias", dateUtc: "2026-07-04T23:00:00Z", team1: { name: "Gan. R32-C", flag: "❓" }, team2: { name: "Gan. R32-D", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 90, phase: "Octavos de Final", group: "Eliminatorias", dateUtc: "2026-07-05T19:00:00Z", team1: { name: "Gan. R32-E", flag: "❓" }, team2: { name: "Gan. R32-F", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 91, phase: "Octavos de Final", group: "Eliminatorias", dateUtc: "2026-07-05T23:00:00Z", team1: { name: "Gan. R32-G", flag: "❓" }, team2: { name: "Gan. R32-H", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 92, phase: "Octavos de Final", group: "Eliminatorias", dateUtc: "2026-07-06T19:00:00Z", team1: { name: "Gan. R32-I", flag: "❓" }, team2: { name: "Gan. R32-J", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 93, phase: "Octavos de Final", group: "Eliminatorias", dateUtc: "2026-07-06T23:00:00Z", team1: { name: "Gan. R32-K", flag: "❓" }, team2: { name: "Gan. R32-L", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 94, phase: "Octavos de Final", group: "Eliminatorias", dateUtc: "2026-07-07T19:00:00Z", team1: { name: "Gan. R32-M", flag: "❓" }, team2: { name: "Gan. R32-N", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },
    { id: 95, phase: "Octavos de Final", group: "Eliminatorias", dateUtc: "2026-07-07T23:00:00Z", team1: { name: "Gan. R32-O", flag: "❓" }, team2: { name: "Gan. R32-P", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }] },

    // ===== CUARTOS DE FINAL (4 partidos) =====
    { id: 96, phase: "Cuartos de Final", group: "Eliminatorias", dateUtc: "2026-07-09T19:00:00Z", team1: { name: "Gan. 8vos-A", flag: "❓" }, team2: { name: "Gan. 8vos-B", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 97, phase: "Cuartos de Final", group: "Eliminatorias", dateUtc: "2026-07-09T23:00:00Z", team1: { name: "Gan. 8vos-C", flag: "❓" }, team2: { name: "Gan. 8vos-D", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 98, phase: "Cuartos de Final", group: "Eliminatorias", dateUtc: "2026-07-10T19:00:00Z", team1: { name: "Gan. 8vos-E", flag: "❓" }, team2: { name: "Gan. 8vos-F", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 99, phase: "Cuartos de Final", group: "Eliminatorias", dateUtc: "2026-07-11T19:00:00Z", team1: { name: "Gan. 8vos-G", flag: "❓" }, team2: { name: "Gan. 8vos-H", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },

    // ===== SEMIFINALES (martes 14 y miércoles 15 de julio) =====
    { id: 100, phase: "Semifinales", group: "Eliminatorias", dateUtc: "2026-07-15T00:00:00Z", team1: { name: "Gan. Cuartos-A", flag: "❓" }, team2: { name: "Gan. Cuartos-B", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },
    { id: 101, phase: "Semifinales", group: "Eliminatorias", dateUtc: "2026-07-16T00:00:00Z", team1: { name: "Gan. Cuartos-C", flag: "❓" }, team2: { name: "Gan. Cuartos-D", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },

    // ===== TERCER PUESTO (sábado 18 de julio) =====
    { id: 102, phase: "Tercer Puesto", group: "Eliminatorias", dateUtc: "2026-07-18T22:00:00Z", team1: { name: "Perdedor Semi 1", flag: "❓" }, team2: { name: "Perdedor Semi 2", flag: "❓" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] },

    // ===== GRAN FINAL (domingo 19 de julio de 2026) =====
    { id: 103, phase: "Gran Final", group: "Eliminatorias", dateUtc: "2026-07-19T22:00:00Z", team1: { name: "Gan. Semi 1", flag: "🏆" }, team2: { name: "Gan. Semi 2", flag: "🏆" }, channels: [{ id: "dsports", name: "DSports", class: "channel-dsports" }, { id: "rcn", name: "RCN", class: "channel-rcn" }, { id: "caracol", name: "Caracol", class: "channel-caracol" }] }
];

// Favoritos por defecto (se sobrescribe con localStorage)
const DEFAULT_FAVORITES = ["Brasil", "Alemania", "Países Bajos", "Bélgica", "España", "Uruguay", "Francia", "Argentina", "Portugal", "Inglaterra", "Colombia"];
